name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Composer
      uses: php-actions/composer@v6
      with:
        php_extensions: sockets
    - name: PHPStan
      uses: php-actions/phpstan@v3
      with:
        path: src/
